########################## è‡ªå®šä¹‰ ##########################

[[rulesets]]
group = "ğŸ¼ å…¨çƒç›´è¿"
ruleset = "rules/force-direct.txt"
interval = 86400

[[rulesets]]
group = "ğŸª Match"
ruleset = "rules/force-proxy.txt"
interval = 86400

######################## åŸºäºæœåŠ¡ ########################

[[rulesets]]
group = "ğŸ» Chat"
ruleset = "rules/chat.txt"
interval = 86400

[[rulesets]]
group = "ğŸ» Chat"
ruleset = "rules/openai.txt"
interval = 86400

############## é»‘åå•æ¨¡å¼: åŒ¹é…èµ°ä»£ç† ##############
# [[rulesets]]
# group = "ğŸŒ» èŠ‚ç‚¹é€‰æ‹©"
# ruleset = "rules/proxy.txt"
# interval = 86400
#
# [[rulesets]]
# group = "ğŸŒ» èŠ‚ç‚¹é€‰æ‹©"
# ruleset = "rules/gfw.txt"
# interval = 86400


############## ç™½åå•æ¨¡å¼: åŒ¹é…èµ°ç›´è¿ ##############

[[rulesets]]
group = "ğŸ¼ å…¨çƒç›´è¿"
ruleset = "rules/direct.txt"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "rules/lan_cidr.txt"
interval = 86400

########################## æœªåŒ¹é… ##########################

[[rulesets]]
group = "ğŸª Match"
ruleset = "MATCH"
